#!/usr/bin/env node
// upstream-surface.mjs - write watch/surface.json: the Foundry and dnd5e names each public repo's
// shipped code uses, read from the sibling clones.
//
// The upstream watch (tools/upstream-watch.mjs) runs in a GitHub Action with no clones, so it
// matches release notes and the dnd5e tag diff against this file to turn each repo's checklist row
// into leads. Generated, never hand-kept: rerun it with the integration map and commit the result.
//
//   node tools/upstream-surface.mjs            write watch/surface.json
//   node tools/upstream-surface.mjs --check    exit 1 if the file is stale
//
// Read-only on the siblings. Tests, tools, docs and scratch are left out: a lead should point at
// code a world runs.

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const OUT = join(ROOT, "watch", "surface.json");
const SKIP_DIRS = new Set(["node_modules", "dist", ".git", ".claude", "prototypes", "shelved", "audits",
  "docs", "history", "scratch", "tools", "test", "tests", "scripts-dev"]);
const SOURCE = /\.(m?js|ts)$/;
const NOT_SHIPPED = /\.test\.|\.bundle\.|\/tests?\//;

const { repos } = JSON.parse(readFileSync(join(ROOT, "repos.json"), "utf8"));
const tracked = repos.filter((r) => r.visibility === "public" && r.status === "active" && ["mod", "mcp"].includes(r.kind));

function walk(dir, out = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (SKIP_DIRS.has(entry.name)) continue;
    const p = join(dir, entry.name);
    if (entry.isDirectory()) walk(p, out);
    else if (SOURCE.test(entry.name) && !NOT_SHIPPED.test(p.replace(/\\/g, "/"))) out.push(p);
  }
  return out;
}

// A document hook names its document: createActiveEffect, preUpdateToken, deleteCombat.
const DOC_HOOK = /^(?:pre)?(?:create|update|delete)([A-Z]\w+)$/;
// Namespace segments, not names a release note would mention.
const GENERIC = new Set(["api", "apps", "implementation", "ux", "elements", "fields", "types", "sheets", "hud",
  "layers", "placeables", "handlebars", "collections", "abstract", "instances", "values", "keys", "entries", "get"]);
// The server routes the bridge and the deploy scripts drive.
const ROUTE = /["'`](?:\$\{[^}]+\})?\/(join|setup|auth|upload|license|api\/status)\b/g;

const surface = {};
const missing = [];
for (const r of tracked) {
  const dir = join(ROOT, r.name);
  if (!existsSync(join(dir, ".git")) || !statSync(join(dir, ".git")).isDirectory()) { missing.push(r.name); continue; }
  const sets = { dnd5eHooks: new Set(), coreHooks: new Set(), documents: new Set(), dnd5eConfig: new Set(), api: new Set(), routes: new Set() };
  for (const f of walk(dir)) {
    const s = readFileSync(f, "utf8");
    // Hooks.on/once, and Battle Flow's listen(name, tag, fn) wrapper.
    for (const m of s.matchAll(/\b(?:Hooks\.(?:on|once)|listen)\(\s*["'`]([\w.]+)["'`]/g)) {
      const h = m[1];
      if (h.startsWith("dnd5e.")) sets.dnd5eHooks.add(h);
      else if (!h.includes(".")) {
        sets.coreHooks.add(h);
        const doc = h.match(DOC_HOOK)?.[1];
        if (doc) sets.documents.add(doc);
      }
    }
    for (const m of s.matchAll(/CONFIG\.DND5E\.(\w+)/g)) sets.dnd5eConfig.add(m[1]);
    for (const m of s.matchAll(/foundry\.(?:utils|documents|canvas|applications|data|dice|audio)\.(?:[\w]+\.)*(\w+)/g)) {
      if (!GENERIC.has(m[1])) sets.api.add(m[1]);
    }
    for (const m of s.matchAll(ROUTE)) sets.routes.add(`/${m[1]}`);
  }
  surface[r.name] = Object.fromEntries(Object.entries(sets).map(([k, v]) => [k, [...v].sort()]));
}

const text = `${JSON.stringify({ $comment: "Generated by tools/upstream-surface.mjs from the sibling clones. Do not edit; rerun it.", repos: surface }, null, 2)}\n`;
if (missing.length) {
  console.error(`not cloned here: ${missing.join(", ")}; run .\\sync.ps1 first`);
  process.exit(1);
}
if (process.argv.includes("--check")) {
  const old = existsSync(OUT) ? readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (old !== text) { console.error("watch/surface.json is stale: run node tools/upstream-surface.mjs"); process.exit(1); }
  console.log("watch/surface.json is current");
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, text);
  const n = (k) => Object.values(surface).reduce((a, s) => a + s[k].length, 0);
  console.log(`wrote watch/surface.json: ${Object.keys(surface).length} repos, ${n("dnd5eHooks")} dnd5e hooks, ${n("coreHooks")} core hooks, ${n("dnd5eConfig")} CONFIG.DND5E keys, ${n("api")} API names, ${n("routes")} routes`);
}
